# Generated by Django 4.0.1 on 2022-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='number_phone',
            field=models.CharField(default=89779746047, max_length=100, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
