# Generated by Django 4.0.1 on 2022-04-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_client_number_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(null=True, verbose_name='Коментарии к заказу')),
                ('delivery', models.BooleanField(verbose_name='Доставка')),
                ('message_order', models.TextField(null=True, verbose_name='Примечания к заказу')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.basket', verbose_name='Корзина')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.client', verbose_name='Клиент')),
                ('status_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.statusorder', verbose_name='Статус заказа')),
            ],
        ),
    ]
