# Generated by Django 4.0.1 on 2022-04-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0006_remove_order_basket_orderproducts_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.order', verbose_name='Заказ'),
        ),
    ]
