# Generated by Django 4.0.1 on 2022-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0007_alter_orderproducts_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status_name',
            field=models.CharField(default='Заказ в пути', max_length=25, verbose_name='Статус'),
        ),
    ]
