# Generated by Django 3.2.9 on 2022-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0009_alter_statusorder_status_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
