# Generated by Django 3.2.9 on 2022-04-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0010_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(related_name='related_order', to='Basket.OrderProducts', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='Basket.order', verbose_name='заказ'),
        ),
    ]
