# Generated by Django 3.2.9 on 2022-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0011_auto_20220425_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(blank=True, related_name='related_order', to='Basket.OrderProducts', verbose_name='Продукты'),
        ),
    ]
